version: "3.9"
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: on-failure
    volumes:
      - ../data:/var/lib/mongodb
    ports:
      - "27017:27017"
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - "3306:3306"

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  enterprise:
    image: enterprise:latest
    container_name: enterprise
    depends_on:
      - db
      - eureka-server
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
    ports:
      - "8082:8082"
    restart: on-failure

  filiale:
    image: filiale:latest
    container_name: filiale
    depends_on:
      - mongodb
      - eureka-server
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
    ports:
      - "8084:8084"
    restart: on-failure
  
  gateway:
    image: gateway:latest
    container_name: gateway
    depends_on:
      - enterprise
      - filiale
    ports:
      - "8080:8080"
    restart: on-failure